import { Octokit } from "@octokit/core";

//as a temporary "solution" I went with some random generated names 
const mockResponse = [
    "Harvey Clayton",
    "Jordanne Bernard",
    "Inaaya Solomon",
    "Gethin Edwards",
    "Abigail Booker",
    "Frederic Collins",
    "Olive Carter",
    "Kelsie Parks",
    "Brittney Sampson",
    "Emmanuel Mclaughlin",
    "Miriam Norman",
    "Tasneem Khan",
    "Marianne Lopez",
    "Cohen Peterson",
    "Bill Miller",
    "Mariyah Hull",
    "Flynn Gill",
    "Sylvie Wallace",
    "Walter Torres",
    "Marshall Rios",
    "Abdulrahman Dorsey",
    "Rose Ward",
    "Ana O'Brien",
    "Margie Bates",
    "Mattie Allen",
    "Jean Hines",
    "Shane Clements",
    "Saoirse Kidd",
    "Ida Rangel",
    "Shivam Mosley",
    "Hiba Bradshaw",
    "Elisa Small",
    "Archie Wilcox",
    "Herbert Turner",
    "Philippa Booth",
    "Daniel Richard",
    "Rayhan Crane",
    "Elmer Hawkins",
    "Oisin Hewitt",
    "Aiden Montes",
    "Aarav Hardy",
    "Taylor Goodwin",
    "Laurence Odom",
    "Lana Phillips",
    "Jasper Santana",
    "Sulayman Tucker",
    "Jac Mejia",
    "Reuben Henry",
    "Anoushka Valentine",
    "Jaydon Hickman",
    "Fahad Conley",
    "Simon Pollard",
    "Aliyah Pace",
    "Alissa O'Quinn",
    "Tiago Giles",
    "Raihan Nash",
    "Mustafa Calderon",
    "Diane Schaefer",
    "Gerald Lawson",
    "Tomos Cook",
    "Floyd Mora",
    "Mariam Christensen",
    "Eva Thornton",
    "Dylan O'Sullivan",
    "Sadie Spencer",
    "Kaitlin Stewart",
    "Denis Levy",
    "Kiara Mooney",
    "Keaton Murphy",
    "Ollie Joseph",
    "Keira Cooper",
    "Emilie Pittman",
    "Lyndon Valdez",
    "Lorna Parsons",
    "Emilia Mullins",
    "Seth Hayden",
    "Josie Shannon",
    "Alan Campos",
    "Sonia Mcintosh",
    "Jonathan Roberson",
    "Laurie Hendrix",
    "Imogen Bridges",
    "Eleni Mendez",
    "Sydney York",
    "Stevie Hubbard",
    "Julius Perez",
    "Leighton Bolton",
    "Wilma Meadows",
    "Caspar Grant",
    "Elin Mendoza",
    "Herbie Campbell",
    "Paul King",
    "Aran Mann",
    "Abu Suarez",
    "Sumaiya Carson",
    "Mina Rosario",
    "Elif Andersen",
    "Callie Singleton",
    "Sulaiman Gregory",
    "Edgar Moreno",
]

// Blocker: 
// https://github.com/community/community/discussions/40619

const useRequest = async () => {
    const octokit = new Octokit({
        auth: process.env.GITHUB_TOCKEN
    });

    // const res = await octokit.request('GET /search/users', {
    //     mode: 'no-cors',
    //     q: 'ivakhiv',
    //     headers: {
    //         'X-GitHub-Api-Version': '2022-11-28',
    //     },
    // });

    return mockResponse;
}

export default useRequest;